"""add editable seo landing pages

Revision ID: 20260820_0007
Revises: 20260815_0006
Create Date: 2026-08-20 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260820_0007"
down_revision: str | Sequence[str] | None = "20260815_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TABLE seo_landing_pages (
            slug TEXT PRIMARY KEY,
            product_type TEXT NOT NULL,
            path_en TEXT NOT NULL,
            path_bg TEXT NOT NULL,
            meta_title_en TEXT NOT NULL,
            meta_title_bg TEXT,
            meta_description_en TEXT NOT NULL,
            meta_description_bg TEXT,
            eyebrow_en TEXT NOT NULL,
            eyebrow_bg TEXT,
            title_en TEXT NOT NULL,
            title_bg TEXT,
            intro_en TEXT NOT NULL,
            intro_bg TEXT,
            note_en TEXT NOT NULL,
            note_bg TEXT,
            shop_all_label_en TEXT NOT NULL,
            shop_all_label_bg TEXT,
            section_title_en TEXT NOT NULL,
            section_title_bg TEXT,
            empty_text_en TEXT NOT NULL,
            empty_text_bg TEXT,
            benefits_title_en TEXT NOT NULL,
            benefits_title_bg TEXT,
            faq_title_en TEXT NOT NULL,
            faq_title_bg TEXT,
            benefits_en TEXT NOT NULL,
            benefits_bg TEXT,
            is_published INTEGER NOT NULL DEFAULT 1 CHECK (is_published IN (0, 1)),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE seo_landing_faq_items (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            page_slug TEXT NOT NULL REFERENCES seo_landing_pages(slug) ON DELETE CASCADE,
            question_en TEXT NOT NULL,
            question_bg TEXT,
            answer_en TEXT NOT NULL,
            answer_bg TEXT,
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_published INTEGER NOT NULL DEFAULT 1 CHECK (is_published IN (0, 1)),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX idx_seo_landing_faq_items_page_order
            ON seo_landing_faq_items(page_slug, sort_order);

        CREATE TRIGGER seo_landing_pages_updated_at
        BEFORE UPDATE ON seo_landing_pages
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();

        CREATE TRIGGER seo_landing_faq_items_updated_at
        BEFORE UPDATE ON seo_landing_faq_items
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();

        INSERT INTO seo_landing_pages (
            slug, product_type, path_en, path_bg,
            meta_title_en, meta_title_bg, meta_description_en, meta_description_bg,
            eyebrow_en, eyebrow_bg, title_en, title_bg, intro_en, intro_bg,
            note_en, note_bg, shop_all_label_en, shop_all_label_bg,
            section_title_en, section_title_bg, empty_text_en, empty_text_bg,
            benefits_title_en, benefits_title_bg, faq_title_en, faq_title_bg,
            benefits_en, benefits_bg,
            is_published
        ) VALUES (
            'handmade-candles', 'candles', '/handmade-candles', '/rachno-izraboteni-sveshti',
            'Handmade Candles | Atelier Marie', 'Ръчно изработени свещи | Ателие Мари',
            'Shop handmade candles from Atelier Marie: small-batch scents, gift-ready presentation, and custom candle options.',
            'Разгледайте ръчно изработени свещи от Ателие Мари: малки серии, подаръчна визия и възможности за персонална поръчка.',
            'Handmade candles', 'Ръчно изработени свещи',
            'Handmade candles for warm, thoughtful spaces', 'Ръчно изработени свещи за уют и специални моменти',
            'Discover Atelier Marie candles poured in small batches for quiet rituals, personal gifts, and seasonal moments. Each piece is finished with care, from scent and wax to packaging.',
            'Открийте свещи от Ателие Мари, изработени в малки серии за уютен дом, личен подарък и сезонни поводи. Всяко изделие е подготвено с внимание към аромат, финиш и представяне.',
            'Looking for something personal? Custom candles and gift sets can be prepared for birthdays, holidays, weddings, and intimate celebrations.',
            'Търсите нещо лично? Можем да подготвим персонални свещи и подаръчни комплекти за рожден ден, празник, сватба или друг специален повод.',
            'Shop all products', 'Разгледай всички продукти',
            'Current candle collection', 'Актуална колекция свещи',
            'The candle collection is being refreshed. Browse the full shop for available handmade pieces.',
            'Колекцията със свещи се обновява. Разгледайте магазина за налични ръчно изработени изделия.',
            'Why choose Atelier Marie candles?', 'Защо свещи от Ателие Мари?',
            'Handmade candle questions', 'Въпроси за ръчно изработени свещи',
            '["Small-batch handmade production","Gift-ready details and careful packaging","Custom options for personal occasions"]',
            '["Ръчна изработка в малки серии","Грижа към детайла и подаръчна визия","Персонални варианти за специални поводи"]',
            1
        ) ON CONFLICT DO NOTHING;

        INSERT INTO seo_landing_faq_items (
            page_slug, question_en, question_bg, answer_en, answer_bg, sort_order, is_published
        ) VALUES
            (
                'handmade-candles', 'Are Atelier Marie candles handmade?', 'Свещите на Ателие Мари ръчно изработени ли са?',
                'Yes. Atelier Marie candles are prepared in small batches with attention to scent, finish, and presentation.',
                'Да. Свещите се подготвят в малки серии с внимание към аромат, финиш и представяне.',
                0, 1
            ),
            (
                'handmade-candles', 'Can I order a custom candle?', 'Мога ли да поръчам персонална свещ?',
                'Yes. Use the contact page to share the occasion, timing, preferred style, and any names or details you want included.',
                'Да. Изпратете ни повод, срок, предпочитан стил и детайли като име, цвят или тема чрез страницата за контакт.',
                1, 1
            ),
            (
                'handmade-candles', 'Are the candles suitable as gifts?', 'Подходящи ли са свещите за подарък?',
                'Yes. The candles are designed to feel gift-ready, with careful finishing and packaging for personal occasions.',
                'Да. Свещите са създадени с подаръчна визия, внимателен финиш и опаковка за лични поводи.',
                2, 1
            )
        ON CONFLICT DO NOTHING;

        SELECT setval(
            pg_get_serial_sequence('seo_landing_faq_items', 'id'),
            COALESCE((SELECT MAX(id) FROM seo_landing_faq_items), 1)
        );
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        DROP TRIGGER IF EXISTS seo_landing_faq_items_updated_at ON seo_landing_faq_items;
        DROP TRIGGER IF EXISTS seo_landing_pages_updated_at ON seo_landing_pages;
        DROP TABLE IF EXISTS seo_landing_faq_items CASCADE;
        DROP TABLE IF EXISTS seo_landing_pages CASCADE;
        """
    )
