"""add editable homepage content

Revision ID: 20260808_0005
Revises: 20260806_0004
Create Date: 2026-08-08 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260808_0005"
down_revision: str | Sequence[str] | None = "20260806_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TABLE home_sections (
            slug TEXT PRIMARY KEY,
            type TEXT NOT NULL CHECK (type IN (
                'hero', 'featured_products', 'text_image', 'text_band', 'cards',
                'timeline', 'collections', 'category_links', 'cta_band'
            )),
            heading_en TEXT NOT NULL,
            heading_bg TEXT,
            subheading_en TEXT,
            subheading_bg TEXT,
            body_en TEXT,
            body_bg TEXT,
            cta_label_en TEXT,
            cta_label_bg TEXT,
            cta_href TEXT,
            image_id TEXT,
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_published INTEGER NOT NULL DEFAULT 1 CHECK (is_published IN (0, 1)),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE home_items (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            section TEXT NOT NULL REFERENCES home_sections(slug) ON DELETE CASCADE,
            title_en TEXT NOT NULL,
            title_bg TEXT,
            text_en TEXT,
            text_bg TEXT,
            image_id TEXT,
            link_href TEXT,
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_published INTEGER NOT NULL DEFAULT 1 CHECK (is_published IN (0, 1)),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX idx_home_items_section_order
            ON home_items(section, sort_order);

        CREATE TRIGGER home_sections_updated_at
        BEFORE UPDATE ON home_sections
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();

        CREATE TRIGGER home_items_updated_at
        BEFORE UPDATE ON home_items
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();

        INSERT INTO home_sections (
            slug, type, heading_en, heading_bg, subheading_en, subheading_bg,
            body_en, body_bg, cta_label_en, cta_label_bg, cta_href, sort_order, is_published
        ) VALUES
            (
                'hero', 'hero', 'Atelier Marie', 'Ателие Мари',
                'Hand-poured in small batches', 'Ръчно наливане в малки серии',
                'Handmade candles, soft scents, and gift-ready details crafted with a premium organic wax blend.',
                'Ръчно изработени свещи, меки аромати и детайли за подарък, създадени с премиум органична восъчна смес.',
                'Shop Collection', 'Разгледай колекцията', '/products', 0, 1
            ),
            (
                'featured', 'featured_products', 'Featured pieces', 'Препоръчани изделия',
                'Editor''s picks', 'Избор от ателието',
                'A curated glimpse at current atelier favorites, with texture, price, and product details close at hand.',
                'Подбран поглед към актуални любими изделия с текстура, цена и детайли за продукта наблизо.',
                NULL, NULL, NULL, 1, 1
            ),
            (
                'trust', 'cards', 'A short note from the atelier', 'Кратка бележка от ателието',
                'Made by hand', 'Изработено на ръка',
                'Each piece is prepared in small batches with careful finishing, selected fragrance blends, and materials chosen for a refined home feel.',
                'Всяко изделие се подготвя в малки серии с внимателен финиш, подбрани ароматни смеси и материали за изискано усещане у дома.',
                NULL, NULL, NULL, 2, 1
            ),
            (
                'categories', 'category_links', 'Choose a handmade category', 'Избери ръчно изработена категория',
                'Shop by mood', 'Пазарувай по настроение',
                'Discover our current handmade collections, gathered by mood and craft.',
                'Открийте настоящите ни ръчно изработени колекции, подбрани по настроение и занаят.',
                NULL, NULL, NULL, 3, 1
            )
        ON CONFLICT DO NOTHING;

        INSERT INTO home_items (
            section, title_en, title_bg, text_en, text_bg, sort_order, is_published
        ) VALUES
            (
                'trust', 'Handmade slowly', 'Бавна ръчна изработка',
                'Every candle is poured, finished, and checked by hand in the atelier.',
                'Всяка свещ се налива, завършва и проверява на ръка в ателието.',
                0, 1
            ),
            (
                'trust', 'Premium organic wax', 'Премиум органичен восък',
                'The wax blend is selected for a clean finish, elegant texture, and consistent quality.',
                'Восъчната смес е подбрана за чист финиш, елегантна текстура и постоянно качество.',
                1, 1
            ),
            (
                'trust', 'Refined scents', 'Изискани аромати',
                'Fragrances are chosen to feel soft, warm, and beautiful at home.',
                'Ароматите са избрани да се усещат меки, топли и красиви у дома.',
                2, 1
            ),
            (
                'trust', 'Gift-ready care', 'Грижа за подарък',
                'Presentation, finish, and support are part of the Atelier Marie experience.',
                'Представянето, финишът и личното съдействие са част от преживяването Ателие Мари.',
                3, 1
            )
        ON CONFLICT DO NOTHING;

        SELECT setval(
            pg_get_serial_sequence('home_items', 'id'),
            COALESCE((SELECT MAX(id) FROM home_items), 1)
        );
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        DROP TRIGGER IF EXISTS home_items_updated_at ON home_items;
        DROP TRIGGER IF EXISTS home_sections_updated_at ON home_sections;
        DROP TABLE IF EXISTS home_items CASCADE;
        DROP TABLE IF EXISTS home_sections CASCADE;
        """
    )
